version: '3.3'

services:

  postgres_db:
    image: postgres:latest
    ports:
        - '5000:5000'
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: postgresdb
    volumes:
      - './mypostgresql/data:/var/lib/postgresql/data'

  goChain:
    depends_on: 
    - "postgres_db"
    image: blockchain/gochain
    links: 
    - postgres_db
    build:
     context: .
     dockerfile: Dockerfile
    environment:
        IP: 0.0.0.0
        PORT: 8000
        POSTGRES_URL: postgres_db
        POSTGRES_PASSWORD: password
    ports:
        - '8000:8000'
